### ISSUE TITLE
Add an option for no/minimal profile pictures

### ISSUE THREAD

**Issue by mohd-akram** [thomaswang/minimal-twitter#48]
Thanks for this awesome extension, it hides some things that I didn't even know bothered me! I think it would be nice to have an option to hide profile pictures next to tweets, or make them a solid color. I was playing around with some CSS, and based on [this](http://www.ephestione.it/dominant-color-of-image-as-background-of-div-all-in-css/), came up with:

```css
background-size: 0.1px;
background-repeat: repeat;
```

This should show the dominant color as the profile picture when added to the div with the `background-image`.

EDIT: Seems like this simpler version produces better results:

```css
article [style*="profile_images"] {
  background-size: 9999px;
}
```

Some more tweaks to make it smaller:

```css
article > div > div > div > div:first-child > div > div, /* above profile pic */
[data-testid="tweet"] > div, /* profile pic */
section > div > div > div > div > div > a > div > div, /* ... show this thread */
article > div > a > div > div, /* show this thread */
section > div > div > div > div > div > div > div > div /* show replies */
{
  flex-basis: 20px !important;
}

[data-testid="tweet"] > div > div > div > a, /* profile pic */
article > div > a > div > div > div > div:last-child /* profile pic - show this thread */
{
  width: 20px !important;
  height: 20px !important;
}
```
